# Note: This script was completely generated by ChatGPT
# This script converts VTK data from ParaView to a CSV file.
from paraview.simple import *
import pandas as pd
import vtk

# Get the active source
src = GetActiveSource()
if not src:
    raise RuntimeError("No active source selected.")

# Update and fetch the data to client
src.UpdatePipeline()
data = servermanager.Fetch(src)

# Assume point data (can change to cell data if needed)
num_points = data.GetNumberOfPoints()
coords = [data.GetPoint(i) for i in range(num_points)]
df = pd.DataFrame(coords, columns=['x', 'y', 'z'])

# Get point data
point_data = data.GetPointData()
for i in range(point_data.GetNumberOfArrays()):
    array = point_data.GetArray(i)
    if not array:
        continue
    name = array.GetName()
    num_components = array.GetNumberOfComponents()

    if num_components == 1:
        df[name] = [array.GetTuple1(j) for j in range(num_points)]
    else:
        for c in range(num_components):
            df[f"{name}_{c}"] = [array.GetTuple(j)[c] for j in range(num_points)]

# Save to CSV
output_path = rf"C:\Users\ZHUCK\Uni\UROP25\FCNResNet_Segmentation\data\aorta_low_re\ns_rec_lowRe_vtk.csv"
df.to_csv(output_path, index=False)
print(f"Saved CSV to: {output_path}")